### ISSUE TITLE
Support password-based authentication (uses a token after auth step)

### ISSUE THREAD

**Issue by renier** [softlayer/softlayer-go#1]
Session struct can be instrumented with a Login method that checks for a non-blank Password field, and if it exists, does the password authentication, grabs the token and puts it in the api key field, then blanks out the password field.

**Comment by JunliWang** [comment]
from the python implementation, it firstly invokes: SoftLayer_User_Customer::getPortalLoginToken(username, password)
to get a temp token, then use it to invoke: SoftLayer_Account::getCurrentUser()
to get the account, in the account apiAuthenticationKeys contains existing APIKey.

I found: this process works in XML-RPC interface, but not in the REST interface.
according to this post, it is a defect
https://forums.softlayer.com/forum/softlayer-developer-network/implementations/80483-get-api-key-for-user
and looks like it is not solved in the 3.1 api endpoint

**Comment by renier** [comment]
@JunliWang That's right. This will only be solved by supporting XML-RPC. Currently we only support REST. Will be looking into this.

**Comment by JunliWang** [comment]
@renier Is that a way we can push Softlayer to fix it in REST interface, it could save lots of effort in the client side.

**Comment by renier** [comment]
@JunliWang XML-RPC support is ready for review (#12).

Usage example:

```go
func main() {
	// Create a session specifying an XML-RPC endpoint url.
	sess := &session.Session{
		Endpoint: "https://api.softlayer.com/xmlrpc/v3",
	}

	// Get a token from the api using your username and password
	userService := services.GetUserCustomerService(sess)
	token, err := userService.GetPortalLoginToken(username, password, nil, nil)
	if err != nil {
		log.Fatal(err)
	}

	// Add user id and token to the session.
	sess.UserId = *token.UserId
	sess.AuthToken = *token.Hash

	// You have a complete authenticated session now.
	// Call any api from this point on as normal...
	keys, err := userService.Id(sess.UserId).GetApiAuthenticationKeys()
	if err != nil {
		log.Fatal(err)
	}

	log.Println("API Key:", *keys[0].AuthenticationKey)
}
```
