### ISSUE TITLE
cannot unmarshal number into Go struct field Error.code of type string 

### ISSUE THREAD

**Issue by YouHang** [softlayer/softlayer-go#105]
Hi, 
user find that sometime Error.code was number, so Client can't unmarshal it into string:
```
// Error implements the error interface
type Error struct {
	StatusCode int
	Exception  string `json:"code"`
	Message    string `json:"error"`
	Wrapped    error
}
```
#https://github.com/IBM-Cloud/ibm-cloud-developer-tools/issues/53

**Comment by renier** [comment]
Not understanding the problem. Yes, the statuscode is a number. Did you mean it was not sometimes?
