### ISSUE TITLE
pagination for softlayer cli

### ISSUE THREAD

**Issue by YouHang** [softlayer/softlayer-go#107]
Hi,
I want to add pagination into softlayer cli, and I have read the doc about pagination in API and client.

I just want to confirm if the server will return the total number when I use pagination to query? I didn't find any information about this in the response. So I use limit() and offset() to query iteratively until server have no response.

Is this a correct way to implement pagination by using this client?

**Comment by renier** [comment]
Yes, that is the way you would do it.
