### ISSUE TITLE
Issue while creating ssh-key via api for SL

### ISSUE THREAD

**Issue by ficofer** [softlayer/softlayer-go#110]
Team,

I have try via SL api and via terraform and I am getting this error.

Is this normal?

Error creating SSH Key: softlayer-go: could not SoftLayer_Security_Ssh_Key#createObject, HTTP error code: '500'

**Comment by renier** [comment]
if you have tried via SL api, then this is not a softlayer-go or terraform issue. You might not have sufficient permissions or some other problem. You should open a ticket on your softlayer account.
