### ISSUE TITLE
SL return SoftLayer_Exception_NotImplemented when invoking setUserMetadata

### ISSUE THREAD

**Issue by edwardstudy** [softlayer/softlayer-go#111]
Hi, I met a 500 error that returned SoftLayer_Exception_NotImplemented.

```
SoftLayer_Exception_NotImplemented: SoftLayer_Virtual_Guest_Strategy_Behavior_Standard::setUserMetadata is not implemented. (HTTP 500)
```

It occurred when I set user metadata after invoking createObject. And this VM stayed 'Halted' status for 'Setup provision configuration'. I just waited about 30 seconds to retry. So I programed 60 seconds suspend. Is this value OK?

Thanks.

**Comment by renier** [comment]
This is an API error, and not a problem with the library, so closing. But you can post a question on stackoverflow (tagged with "softlayer") for api issues.
