### ISSUE TITLE
Terraform Crashing while provisioning Object Storage Account

### ISSUE THREAD

**Issue by vijaylakshmi-b** [softlayer/softlayer-go#113]
### Terraform Version
~/Work/Terraform/Swift$ terraform version
Terraform v0.11.2
+ provider.ibm (unversioned)

### Affected Resource(s)
- ibm_object_storage_account

### Terraform Configuration Files
resource "ibm_object_storage_account" "storage_account" {
        account_type = "SWIFT"
}
### Additional Information ###
The following function is failing when trying to fetch the billing status
`func CheckBillingOrderStatus(sess *session.Session, receipt *datatypes.Container_Product_Order_Receipt, statuses []string) (bool, *datatypes.Billing_Order_Item, error) {
	service := services.GetBillingOrderItemService(sess)

	item, err := service.
		Id(*receipt.PlacedOrder.Items[0].Id).
		Mask("mask[id,billingItem[id,provisionTransaction[id,transactionStatus[name]]]]").
		GetObject()

	if err != nil {
		return false, nil, err
	}

	currentStatus := *item.BillingItem.ProvisionTransaction.TransactionStatus.Name
	for _, status := range statuses {
		if currentStatus == status {
			return true, &item, nil
		}
	}

	return false, &item, nil
}`
The API `https://api.softlayer.com/rest/v3/SoftLayer_Billing_Order_Item/<billingID>.json?objectMask=mask[id,billingItem[id,provisionTransaction[id,transactionStatus[name]]]]` 
returns the response as 
There are multiple response formats seen while the provisioning is in progress and when it gets completed.
### 1 ###
`{
"id": 355842301
}`

### 2 ###
`{
"id": 355842301,
"billingItem": {
"id": 329944719,
"provisionTransaction": {
"id": 92312507,
"transactionStatus": {
"name": "SERVICE REGISTER"
}
}
}
}`

### 3 ###
`{
"id": 355842301,
"billingItem": {
"id": 329944719,
"provisionTransaction": {
"id": 92312507,
"transactionStatus": {
"name": "CLOUDLAYER_STORAGE_POST_SETUP"
}
}
}
}`

### 4 ###
`{
"id": 355842301,
"billingItem": {
"id": 329944719,
"provisionTransaction": {
"id": 92312507,
"transactionStatus": {
"name": "CLOUDLAYER_STORAGE_CONFIG_CDN"
}
}
}
}`

### 5 ###
`{
"id": 355842301,
"billingItem": {
"id": 329944719,
"provisionTransaction": {
"id": 92312507,
"transactionStatus": {
"name": "COMPLETE"
}
}
}
}`

The code is expecting "transactionStatus in the response and since the first response does not contain that key, it fails.

### Debug Output and Panic Output
https://gist.github.com/vijaylakshmi-b/d159bc7727610cb5a1f7b309eaa4f2ee

### Expected Behavior
Provisioning should complete successfully

### Actual Behavior
Provisioning is done, but terraform crashes while trying to fetch the Billing Status.

### Steps to Reproduce
`terraform apply`

**Comment by renier** [comment]
Open this at https://github.com/IBM-Cloud/terraform-provider-ibm/issues
