### ISSUE TITLE
Understanding equivalent Go procedure -- Bare Metal Ordering

### ISSUE THREAD

**Issue by jwhett** [softlayer/softlayer-go#120]
Hello,

With `slcli` one can simply `slcli order package-list` to get a list of packages. However, all entities in the Go library require a PriceID to order them. What is the equivalent set of Go methods to return the a set or list of _things_/ _packages_ one can order for bare metals? I've not found relevant examples either in the issues here or in the GoDocs. Is there a way to drill down from my Account to a list of available packages and their relevant contents and PriceIDs?

Thank you,
Josh

**Comment by jwhett** [comment]
@whereswaldon FYI

**Comment by acamacho82** [comment]
@jwhett  the `slcli order package-list` calls to the method [Product_Package::getAllObjets](https://softlayer.github.io/reference/services/SoftLayer_Product_Package/getAllObjects)

So the next piece of code should retrieves the same information than the previous slcli command. 

```go
        sess := session.New()
	sess.Endpoint = "https://api.softlayer.com/rest/v3.1"

	service := services.GetProductPackageService(sess)

	objMask := "mask[id,name,keyName,isActive,type]"

	packageList, err := service.Mask(objMask).GetAllObjects()
```

If you want to retrieve only packages for bare metals then you need to filter them by using [object-filters](https://softlayer.github.io/article/object-filters/), then the code should be something like below:

```go
        objFilter := filter.Path("type.keyName").StartsWith("BARE_METAL").Build()

	packageList, err := service.Mask(objMask).Filter(objFilter).GetAllObjects()
```

Once you retrieve the list, then you can select the ID and retrieve the list of items and prices by using the method [Product_Package::getItem](https://softlayer.github.io/reference/services/SoftLayer_Product_Package/getItems) or [Product_Package::getItemPrieces](https://softlayer.github.io/reference/services/SoftLayer_Product_Package/getItemPrices) 

**Some examples:**
https://softlayer.github.io/go/get_item_prices.go/ retrieves the list of prices, just change the package id value.

This another example retrieves prices in package 200 by location https://softlayer.github.io/go/get_item_prices_by_location.go/, there are different packages that can used to order bare metal servers and the package 200 is one of them (Fast servers) 

If you need to retrieve more information from the items and prices then you would need to use [object-masks](https://softlayer.github.io/article/object-masks/)

**Comment by jwhett** [comment]
Thanks for the detailed information, @acamacho82!
