### ISSUE TITLE
notificationOccurrenceEventType ANNOUNCEMENT events not present

### ISSUE THREAD

**Issue by BilboTheGreedy** [softlayer/softlayer-go#124]
it appears that filtering for ANNOUNCEMENT events is not working properly compared to PLANNED and UNPLANNED_INCIDENT. When checking the rest API with [following filters](https://api.softlayer.com/rest/v3.1/SoftLayer_Notification_Occurrence_Event/getAllObjects.json?objectMask=mask%5Bid%2CstartDate%2Csubject%2ClastUpdate%2CnotificationOccurrenceEventType%5D&objectFilter=%7B%22notificationOccurrenceEventType%22%3A+%7B%22keyName%22%3A+%7B%22operation%22%3A+%22ANNOUNCEMENT%22%7D%7D%7D)  it seems fine. 

```

               mask := "id;startDate;subject;lastUpdate;notificationOccurrenceEventType"
		t := time.Now().Add(time.Duration(-24) * time.Hour)
		//Filter by startDate
		filter := fmt.Sprintf(`{
		"startDate":{
			"operation":"greaterThanDate",
			"options":[{
				"name":"date",
				"value":["%s"]
				}]
		}
	}
	`, t.Format("01/02/2006 00:00:00"))
		events, err := NotifyService.Mask(mask).Filter(filter).GetAllObjects()
               if err != nil {
			return
		}
              for _, event := range events {
                     fmt.Println(*event.NotificationOccurrenceEventType.KeyName)
               }
```

**Comment by BilboTheGreedy** [comment]
fixed code block styling

**Comment by renier** [comment]
@BilboTheGreedy have you tried using the filter builder as described here:
* https://github.com/softlayer/softlayer-go/#filter-builder
* https://github.com/softlayer/softlayer-go/blob/master/filter/filters.go#L294

**Comment by BilboTheGreedy** [comment]
@renier Very much appreciated, thanks. Should been using the filter package to begin with.
