### ISSUE TITLE
Update softlayer-go for createFromIcos changes

### ISSUE THREAD

**Issue by khuong507** [softlayer/softlayer-go#129]
There are changes to the createFromIcos config template could you please update?

**Comment by renier** [comment]
@khuong507 which service is that method in?

**Comment by khuong507** [comment]
There is a new datatype in here. https://sldn.softlayer.com/reference/datatypes/SoftLayer_Container_Virtual_Guest_Block_Device_Template_Configuration/

**Comment by renier** [comment]
@khuong507 Which service is that datatype used in?

**Comment by khuong507** [comment]
@renier https://sldn.softlayer.com/reference/services/SoftLayer_Virtual_Guest_Block_Device_Template_Group/createFromIcos/
here is the service.

**Comment by khuong507** [comment]
Softlayer Virtual Guest Block Device Template Group

**Comment by allee8285** [comment]
piggy back to regenerate softlayer-go support on network overlay feature.
