### ISSUE TITLE
No dev instructions about needing httpmock in readme

### ISSUE THREAD

**Issue by renier** [softlayer/softlayer-go#13]
```
$ make
go build ./...
tests/util.go:20:2: cannot find package "github.com/jarcoal/httpmock" in any of:
	/usr/local/go/src/github.com/jarcoal/httpmock (from $GOROOT)
	/Users/renier/Projects/go/src/github.com/jarcoal/httpmock (from $GOPATH)
make: *** [build] Error 1
```

**Comment by renier** [comment]
Should we exclude `tests` from the build?

**Comment by riethm** [comment]
We can try it.  I had the same issue with the xmlrpc lib last night.  We have a `make deps` task which would take care of dependencies, but need to add a `-u` so it updates (or have a separate `update-deps` task.)  Either way, you're right, we should probably mention deps in a Developer section of the README

**Comment by renier** [comment]
@riethm Should we then just make the build target depend on deps? But if so, we should not use -u, as that will always make it go to the network for every build.
