### ISSUE TITLE
Filters Build will ignore already prepared operation if Opts is present

### ISSUE THREAD

**Issue by arielsalvo** [softlayer/softlayer-go#131]
The function already has an `operation` set before analyzing Opts in:
https://github.com/softlayer/softlayer-go/blob/a40f6fdd659fe88efd2020e932905ceb4d496db7/filter/filters.go#L108

And, if Opts is set, the already prepared `operation` is replaced by `filter.Op` overwriting what was already there:
https://github.com/softlayer/softlayer-go/blob/a40f6fdd659fe88efd2020e932905ceb4d496db7/filter/filters.go#L125

I'm actually trying to perform an `orderBy` operation on `createDate` of public images:
```javascript
{"createDate":{"operation":"orderBy","options":[{"name":"sort","value":["DESC"]}]},"name":{"operation":"25GB - Ubuntu / Ubuntu / 18.04-64 Minimal for VSI"}}
```
But all I was able to build was:
```javascript
{"createDate":{"operation":"","options":[{"name":"sort","value":["DESC"]}]},"name":{"operation":"25GB - Ubuntu / Ubuntu / 18.04-64 Minimal for VSI"}}
```

**Comment by renier** [comment]
@arielsalvo Can you show the code that you are running? I'd like to use that to create a unit test.

**Comment by arielsalvo** [comment]
@renier 
I tried several different ways with bad outcomes.
This one had some promise but is a bit of a hack since there is no function to set `filter.Op = orderBy`
```
templateService := services.GetVirtualGuestBlockDeviceTemplateGroupService(sess)
filters := filter.New(filter.Path("name").Eq(name))
  if mostRecent {
    filters = append(filters,
                    filter.Path("createDate").Eq("orderBy").Opt("sort", [1]string{"DESC"}),
    )
}
fmt.Println(filters.Build())
```

I also tried with this, but it didn't work either:
```
                    filter.Path("createDate", "orderBy").Opt("sort", [1]string{"DESC"}),
```

I get the same result with both options:
```
{"createDate":{"operation":"","options":[{"name":"sort","value":["DESC"]}]},"name":{"operation":"25GB - Ubuntu / Ubuntu / 18.04-64 Minimal for VSI"}}
```

Hope it helps
