### ISSUE TITLE
Could we retry a connection reset network error

### ISSUE THREAD

**Issue by edwardstudy** [softlayer/softlayer-go#132]
Hi, guys

We had a network `read: connection reset by peer` error sometimes. SoftLayer team confirmed that when they do upgrades, restart front end or under high load, there could be v brief disruptions like this. 

```
[116870199:softlayerGo] 2019/04/02 15:19:04 [DEBUG] Request URL:  POST https://api.service.softlayer.com/rest/v3.1/SoftLayer_Virtual_Guest.json
[116870199:softlayerGo] 2019/04/02 15:19:04 [DEBUG] Parameters:  {"parameters":[********]}
[116870199:json] 2019/04/02 15:20:02 DEBUG - CloudError response bytes
********************
{"result":null,"error":{"type":"Bosh::Clouds::CloudError","message":"VM failed to create: Creating instance: Post https://api.service.softlayer.com/rest/v3.1/SoftLayer_Virtual_Guest.json: read tcp 10.112.90.101:57738-\u003e10.0.80.88:443: read: connection reset by peer","ok_to_retry":false},"log":""}
********************
```

You can see that we request an API and got this network issue.

Could we retry this error?

**Comment by renier** [comment]
@edwardstudy See https://github.com/softlayer/softlayer-go/blob/master/session/session.go#L133-L137

**Comment by edwardstudy** [comment]
Hi, @renier. I knew this retry mechanism. But I meant that error was not covered.

**Comment by renier** [comment]
@edwardstudy the existing retry mechanism is meant to only cover tcp-level request errors. It is not meant to cover SoftLayer middleware errors. In those cases, given the highly variable range of middleware errors, their undocumented nature, and the fact that you won't want to retry in every case, it's best if that is handled directly by the client application and not the client library itself.

btw, what does `"ok_to_retry":false` mean?

**Comment by edwardstudy** [comment]
@renier I agreed what you said. And this error was too dirty to catch and had not appropriate error code.

About `"ok_to_retry":false` stuff, it's to tell invoker does not retry this action.
