### ISSUE TITLE
There is no PublicIpAddress in Network_LBaaS_LoadBalancerServerInstanceInfo

### ISSUE THREAD

**Issue by YouHang** [softlayer/softlayer-go#140]
Hi, 
There is only PrivateIpAddress in the Network_LBaaS_LoadBalancerServerInstanceInfo,
How can I add a member with public IP address
https://github.com/softlayer/softlayer-go/blob/b9062a914a22c292ef4e4a8e9849531a9da9ac54/datatypes/network.go#L2491

**Comment by allmightyspiff** [comment]
`make generate` will refresh your datatypes folder. While the SoftLayer datatypes/services don't change often, you do need to run `make generate` every time they do. This will pull down all the WSDL definitions, and build the needed go structures for each.

Hope that helps.

**Comment by YouHang** [comment]
got it thanks!
