### ISSUE TITLE
Filters were not working for multi-level

### ISSUE THREAD

**Issue by narkarum** [softlayer/softlayer-go#150]
Example:

```
slcli -v  --format=json call-api SoftLayer_Account getNetworkStorage --limit=1000 --mask="mask[id;serviceResource.datacenter.name]" --json-filter='{"networkStorage":{"datacenter":{"name":{"operation":"mon01"}}}}'
```
Above command is not filtering the datacenter name. It is displaying all volumes and from all datacenters.

**Comment by narkarum** [comment]
Example:

--json-filter='{"networkStorage":{"datacenter":{"name":{"operation":"mon01"}}}}'

**Comment by allmightyspiff** [comment]
Hey @narkarum , Issues with the SLCLI go in [softlayer-python ](https://github.com/softlayer/softlayer-python/issues)

That being said, your filter is not quite correct, try the following.
```
slcli -v  --format=json call-api SoftLayer_Account getNetworkStorage --limit=1000 --mask="mask[id;serviceResource.datacenter.name]" --json-filter='{"networkStorage":{"serviceResource":{"datacenter":{"name":{"operation":"mon01"}}}}}'

```
