### ISSUE TITLE
add new function SoftLayer_Network_Storage::refreshDuplicate()

### ISSUE THREAD

**Issue by YouHang** [softlayer/softlayer-go#154]
Hi,
according to the issue:https://github.ibm.com/Bluemix/bluemix-cli/issues/3241

IMS service SoftLayer_Network_Storage::refreshDependentDuplicate() is being deprecated. And we should start using SoftLayer_Network_Storage::refreshDuplicate() instead.

But it seems that softlayer-go doesn't support this command for now

**Comment by allmightyspiff** [comment]
When this feature is released I'll update the service/datatypes data to match. The feature is currently being tested in QE, so assuming no code changes are required, should be released on the 9th.

**Comment by allmightyspiff** [comment]
`func (r Network_Storage) RefreshDuplicate(snapshotId *int) (resp bool, err error) {` exists now
https://github.com/softlayer/softlayer-go/blob/master/services/network.go#L8498
