### ISSUE TITLE
function "AllowAccessFromHost" return nil

### ISSUE THREAD

**Issue by jiangbo202** [softlayer/softlayer-go#179]
function "AllowAccessFromHost" should return datatypes.Network_Storage_Allowed_Host, but I got nil.

```	
allowhost, err := service.Id(1111111).AllowAccessFromHost(&typename, &hostid)  
if err != nil {   
     fmt.Printf("err: %v\n", err)  
}  
fmt.Printf("allowhost: %v\n", allowhost)    
==========
return info:
allowhost: <nil>
```
I also try to use mask:
```
mask:="id;name"
allowhost, err := service.Id(1111111).Mask(mask).AllowAccessFromHost(&typename, &hostid) 
```
but I also got nil.  
by my debug, http status code is 200, but no other information is returned

Please help me check where is the problem

**Comment by allmightyspiff** [comment]
@jiangbo202 It looks like while https://sldn.softlayer.com/reference/services/SoftLayer_Network_Storage/allowAccessFromHost/ (and some of the other similar methods) don't return any data like the docs say it should, those methods do still modify access properly at least. I'll mention this to our storage team as a bug, thanks for letting us know.
If that method fails to modify permissions, you would get an exception back,

The https://sldn.softlayer.com/reference/services/SoftLayer_Network_Storage/allowAccessFromHostList/ method looks like it returns data though, so you might be able to use that if needed.

**Comment by jiangbo202** [comment]
"allowAccessFromHostList" can return valid information, which meets my needs, thinks
