### ISSUE TITLE
the parameter of Product_Order.VerifyOrder() is not correct

### ISSUE THREAD

**Issue by JunliWang** [softlayer/softlayer-go#20]
it is using *datatypes.Container_Product_Order, but for a particular type, eg. Network_Subnet, it requires extra property like vlanId set on this type Container_Product_Order_Network_Subnet, so this parameter should use  interface{} like PlaceOrder() uses.
Otherwise, sl responses with this error:
{"error":"An endpoint VLAN is required to order a portable subnet.","code":"SoftLayer_Exception_Public"}

**Comment by renier** [comment]
@JunliWang Please try the _verify-order_ branch and let me know if that works for you.

**Comment by JunliWang** [comment]
@renier, it works great, thank you!
