### ISSUE TITLE
Does this lib work with Bluemix

### ISSUE THREAD

**Issue by TamalSaha** [softlayer/softlayer-go#21]
Hi,
I have signed up for BlueMix and I see that I can create SoftLayer compute resources using BlueMix's console. Will I be able to create compute resources using this api? Or, is there a separate api for BlueMix compute stuff?

Thanks.

**Comment by renier** [comment]
@TamalSaha It is my understanding that bluemix uses the same softlayer apis. However, you'll need to know the softlayer username and api key that bluemix uses on your behalf, in order to use this library. You'll have to ask around. Try developer.ibm.com/answers/.
