### ISSUE TITLE
nil pointer exception with sl.Get()

### ISSUE THREAD

**Issue by JunliWang** [softlayer/softlayer-go#22]
the intention of this method is to get a value from either primitive or a pointer(default value for nil pointer).
but in sl datatypes, many properties are pointer of pointer(or pointer of pointer of pointer, etc). eg. VirtualGuest.DataCenter.Name
if datacenter is nil, then sl.Get(VirtualGuest.DataCenter.Name) will panic with nil pointer exception.

I'm not sure if there is a better way to handle this other than :
var name 
if VirtualGuest.DataCenter != nil {
   name =  sl.Get(VirtualGuest.DataCenter.Name) 
}

**Comment by renier** [comment]
@JunliWang You basically have to check for nil at every point except the last one:

```
if VirtualGuest.DataCenter != nil {
    name = sl.Get(VirtualGuest.DataCenter.Name)
}
```
