### ISSUE TITLE
make the API UTable

### ISSUE THREAD

**Issue by JunliWang** [softlayer/softlayer-go#24]
I'm writing UT for the CLI commands,  one key issue is, I need to fake those APIs using something like counterfeiter(https://github.com/maxbrunsfeld/counterfeiter, CloudFoundry is using it.)
so the services need to be declared as interface, instead of struct, in order to generate fakes.

**Comment by renier** [comment]
@JunliWang You do that by implementing your own TransportHandler. See the TransportHandler interface in session/session.go.

You can also use httpmock. Take a look at session/rest_test.go for an example.

**Comment by JunliWang** [comment]
I see, thanks!
