### ISSUE TITLE
Trying to understand how to use library

### ISSUE THREAD

**Issue by johntdyer** [softlayer/softlayer-go#25]
Hello,

 I am trying to understand how to go about emulating the following POST using this library. 

curl -n -g --data '{"parameters": ["10.xxx.xxx.xxx"]}' 'https://api.softlayer.com/rest/v3/SoftLayer_Network_Vlan/getVlanForIpAddress?objectMask=mask[id,vlanNumber,networkSpace,primaryRouter]' 

Thanks!

-John

**Comment by renier** [comment]
@johntdyer Have you looked at the exampled directory?

hint: `service := services.GetNetworkVlanService()`
