### ISSUE TITLE
Network_Storage.storageTierLevel should not be a string type

### ISSUE THREAD

**Issue by JunliWang** [softlayer/softlayer-go#27]
Document is wrong:
https://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_Storage

refer to below REST call and response

https://api.softlayer.com/rest/v3.1/SoftLayer_Network_Storage/13923041/getObject.json?objectMask=mask[id, storageTierLevel]

    {
        "id": 13923041,
        "storageTierLevel":
        {
            "allowCancellationFlag": 1,
            "associatedBillingItemId": "123709989",
            "cancellationDate": null,
            "categoryCode": "storage_tier_level",
            "createDate": "2016-08-31T02:09:15-07:00",
            "cycleStartDate": "2016-11-01T02:18:19-07:00",
            "description": "0.25 IOPS per GB",
            "id": 123709993,
            "laborFee": "0",
            "laborFeeTaxRate": "0",
            "lastBillDate": "2016-11-01T02:18:19-07:00",
            "modifyDate": "2016-11-01T02:18:19-07:00",
            "nextBillDate": "2016-12-01T00:00:00-06:00",
            "oneTimeFee": "0",
            "oneTimeFeeTaxRate": "0",
            "orderItemId": 149747285,
            "parentId": 123709989,
            "recurringFee": "0",
            "recurringFeeTaxRate": "0",
            "recurringMonths": 1,
            "serviceProviderId": 1,
            "setupFee": "0",
            "setupFeeTaxRate": "0"
        }
    }

**Comment by JunliWang** [comment]
I raised this problem to 
http://stackoverflow.com/questions/40800048/network-storage-storagetierlevel-should-not-be-a-string-type
hope they can fix it in metadata service.

**Comment by renier** [comment]
@JunliWang Did you get information as to the actual datatype of storageTierLevel? Looks like a billing item.

**Comment by JunliWang** [comment]
@renier ,yes it looks like a billing item, waiting the confirmation from sl guys.

**Comment by JunliWang** [comment]
It is interesting, storageTierLevel actually is a string, 
this request will return a string type  (I don't know how this trick is played or object mask syntax can work like that)
https://api.softlayer.com/rest/v3.1/SoftLayer_Network_Storage/13923041/getObject.json?objectMask=storageTierLevel;id

    {
        "id": 13923041,
        "storageTierLevel": "LOW_INTENSITY_TIER"
    }

the real bug is about a billing item is put into wrong place, so nothing is wrong with metadata or this go-client.
