### ISSUE TITLE
incorrect parameters in SoftLayer_Network_Storage::failbackFromReplicant & SoftLayer_Network_Storage::failoverToReplicant

### ISSUE THREAD

**Issue by JunliWang** [softlayer/softlayer-go#30]
something wrong with the metadata, python client(and xml rpc) is correct, 
I reported this problem to:

http://stackoverflow.com/questions/40861004/extra-parameter-is-required-softlayer-network-storagefailbackfromreplicant

**Comment by renier** [comment]
@JunliWang Could you write up the correct metadata you expect for those methods and show it here?

**Comment by JunliWang** [comment]
looks like the metadata is correct, python client does not honor it by adding extra parameter, which confused me.
