### ISSUE TITLE
replicationStatus of Network_Storage should not be a string type

### ISSUE THREAD

**Issue by JunliWang** [softlayer/softlayer-go#31]
https://api.softlayer.com/rest/v3.1/SoftLayer_Network_Storage/17193175.json?objectMask=mask[id,replicationStatus]

the response is:

    {
        "id": 17193175,
        "replicationStatus":
        {
            "createDate": "2016-12-09T02:18:27-06:00",
            "message": "Replicant Volume Provisioning has completed.",
            "scheduleId": null,
            "typeId": 322,
            "volumeId": 17193173
        }
    }

**Comment by renier** [comment]
@JunliWang Not according to the metadata and the [docs](http://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_Storage).

What you show looks exactly like a [Network Storage Event](http://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_Storage_Event), so I believe you have found another bug in the API.

**Comment by JunliWang** [comment]
Yes, I posted the problem to
http://stackoverflow.com/questions/41093442/replicationstatus-of-network-storage-should-not-be-a-string-type
waiting for the response.

**Comment by renier** [comment]
Workaround posted on [stackoverflow](http://stackoverflow.com/a/41104114/3160958). It is an issue with the object mask handling in the api service.
