### ISSUE TITLE
CPU price lists are filtered by network type not CPU type.

### ISSUE THREAD

**Issue by minsikl** [softlayer/softlayer-go#34]
Helper function `UpgradeVirtualGuest` invokes `product.SelectProductPricesByCategory` to collect price items. It passes `guest.PrivateNetworkOnlyFlag` to filter cpu and network type. However, cpu price list should be filtered by `guest.DedicatedAccountHostOnlyFlag`.

**Comment by renier** [comment]
@minsikl What's left for this?

**Comment by minsikl** [comment]
@renier the patch was applied and the issue can be closed.
