### ISSUE TITLE
Client does not set content-type or accept headers

### ISSUE THREAD

**Issue by sykesm** [softlayer/softlayer-go#39]
While it doesn't seem to impact interactions with the SoftLayer API, while using the client against a mock server I've noticed that the client doesn't set `content-type` or `accept` headers on requests to the server.  Should it?

I've had to stop using some of the built-in http server matchers because of this omission.

**Comment by renier** [comment]
@sykesm No it doesn't have to set those headers. But you are welcome to send a PR for this. @riethm Would you be opposed to accepting a PR for this?
