### ISSUE TITLE
Marshaling of string responses does not always work

### ISSUE THREAD

**Issue by sykesm** [softlayer/softlayer-go#42]
When attempting to get the LunId from an iSCSI volume, the server responds with a string encoded number.

```
$ curl -sngG https://api.softlayer.com/rest/v3/SoftLayer_Network_Storage_Iscsi/20489541/getLunId.json
"194"
```

When using the API, the returned data is does not get unmarshalled so it comes back in the same form.  The following snippet returns `l: "194"` when `l: 194` is expected.

```
l, err := services.GetNetworkStorageService(sess).Id(storageID).GetLunId()
if err != nil {
	return 0, err
}

fmt.Printf("l: %s\n", l)
```

This appears to be due to how strings are handled in the [RestTransport#DoRequest](https://github.com/softlayer/softlayer-go/blob/master/session/rest.go#L102-L103) code where strings are left alone. In general, it would seem that strings should be unmarshalled so the wrapping quotes get removed.

**Comment by renier** [comment]
@sykesm Do you see any other apis that return the string enclosed with double quotes?

since, this is the first time I see this, I'm not sure if we have just missed this from the beginning, or whether there are some apis that return `"194"` and others `194`.

**Comment by sykesm** [comment]
Quick search (`ag 'string, err' $GOPATH/src/github.com/softlayer/softlayer-go/services`) implies >280 services have this issue.

Manually testing a couple:

```
$ curl -sngG https://api.softlayer.com/rest/v3/SoftLayer_Virtual_Guest/28762137/getGlobalIdentifier.json | jq .
"55487464-dbe8-49c4-8c59-ceafd5acfc3f"

$ curl -sngG https://api.softlayer.com/rest/v3/SoftLayer_Network_Storage_Iscsi/20489527/getIops.json | jq .
"200"
```

There may be some that don't have that behavior but I can check a couple.

**Comment by renier** [comment]
> 280 services have this issue

That would be methods, not services.

Ok, will look into it.

**Comment by renier** [comment]
@sykesm Try PR #43

**Comment by sykesm** [comment]
#43 resolves my issue. Thanks.
