### ISSUE TITLE
Timeout due to the short DefaultTimeout

### ISSUE THREAD

**Issue by minsikl** [softlayer/softlayer-go#47]
When XML-RPC protocol is used, sometimes, `SoftLayer_Product_Order::placeOrder` for storage takes more than one minute, and it causes timeout errors. Although timeout value is configurable, it is necessary to support functions with the default value in typical cases. How about changing the default timeout value from  60 secs to 120 secs?

**Comment by renier** [comment]
@minsikl Ok
