### ISSUE TITLE
Filter Builder feature isn't working when using dates values

### ISSUE THREAD

**Issue by acamacho82** [softlayer/softlayer-go#49]
Filter Builder feature isn't working when using dates values, the following code 

```go
filters := filter.Path("invoices.createDate").DateBetween("03/25/2017","04/04/2017").Build()
```

returns or build a raw string like this:

```html
{"invoices":{"createDate":{"operation":"betweenDate","options":[{"name":"startDate","value":"03/25/2017"},{"name":"endDate","value":"04/04/2017"}]}}
```

And it always returns an empty value no matter is uses 04/04/2017, 04/04/17, 2017-04-04 or 04-04-2017

The issue here is that the date value isn't into an array [ ] (for example ["04/04/2017"]). I tested it using a REST call and the following filter returns values between dates: 
```html
{"invoices":{"createDate":{"operation":"betweenDate","options":[{"name":"startDate","value":["03/25/2017"]},{"name":"endDate","value":["04/04/2017"]}]}}
```

There are some usage examples in stackoverflow about date filters:
http://stackoverflow.com/questions/35744591/object-filter-for-inovice-create-date
http://stackoverflow.com/questions/34185043/using-object-filters-with-softlayer-ruby-api
http://stackoverflow.com/questions/43666868/getting-error-internal-error-on-postman-and-getting-error-can-not-deseriali

This issue is reproducible with any date function in **Filter Build** feature.

The workaround on this case is creating the filter using the raw string, like example below.
```go
filters := `{"invoices":{"createDate":{"operation":"betweenDate","options":[{"name":"startDate","value":["03/25/2017"]},{"name":"endDate","value":["04/04/2017"]}]}}}`
```
Regards,

**Comment by renier** [comment]
@acamacho82 Thanks for reporting this. Apparently, [the article on object filters](https://sldn.softlayer.com/article/object-filters) is outdated regarding this.

**Comment by renier** [comment]
@acamacho82 Do you know for a fact if the date enclosed within an array is necessary for the other filters?

* Date
* DateBefore
* DateAfter
* DateBetween

**Comment by acamacho82** [comment]
Yep, I verified them and it's necessary to set the date value within an array (all listed above).
