### ISSUE TITLE
Billing_Order_Quote.GetRecalculatedOrderContainer might have incorrect signature

### ISSUE THREAD

**Issue by mihasya** [softlayer/softlayer-go#54]
While working in some Go code to automate ordering of bare metal machines using quotes. I encountered what I believe to be a bug in [`Billing_Order_Quote.GetRecalculatedOrderContainer`](https://github.com/softlayer/softlayer-go/blob/3675eea10a9ffac5b1cfb0a817c92d384cbadd1d/services/billing.go#L2262). The signature requires a struct as an input that I cannot for the life of me figure out how to produce:

```go
func (r Billing_Order_Quote) GetRecalculatedOrderContainer(userOrderData *datatypes.Container_Product_Order, orderBeingPlacedFlag *bool) (resp datatypes.Container_Product_Order, err error)
```

Looking at the same method in Python, it simply requires an integer `quote_id` (see [python example](https://softlayer.github.io/python/order_quote_advanced/)). Matt Colton confirmed that the python signature is correct and helped me write some code to send a quote Id to that method and get back a `Container_Product_Order`:

```go
func GetRecalculatedOrderContainer(session *session.Session, quoteId int) (container datatypes.Container_Product_Order, err error) {
	opts := sl.Options{
		Id: &quoteId,
	}

	err = session.DoRequest("SoftLayer_Billing_Order_Quote", "getRecalculatedOrderContainer", nil, &opts, &container)

	return
}
```

One additional thing that makes the plot more interesting is that the API docs appear to match the current Go implementation, though also don't make clear how to get a [`Container_Product_Order`](http://sldn.softlayer.com/reference/datatypes/SoftLayer_Container_Product_Order) from a quote. http://sldn.softlayer.com/reference/datatypes/SoftLayer_Container_Product_Order

Cheers!

**Comment by renier** [comment]
@mihasya An example of this is at https://github.com/softlayer/terraform-provider-softlayer/pull/151/files#diff-0e1ed02a67249b4b731d93c1e783da88R137

You could also use the method in the Billing_Order_Quote service, by passing nil as the pointer to the struct. As long as you pass the appropriate context Id (for the quote).

**Comment by mihasya** [comment]
👍 that worked
