### ISSUE TITLE
missing following properties in Network_Storage

### ISSUE THREAD

**Issue by JunliWang** [softlayer/softlayer-go#55]
originalVolumeName, originalVolumeSize,originalSnapshotName
and corresponding GetXXX() in service
they are required for duplicating volume (a new feature in CLI)
I can find them in metadata: https://api.softlayer.com/metadata/v3.1 
and document: https://sldn.softlayer.com/reference/datatypes/SoftLayer_Network_Storage

**Comment by renier** [comment]
@JunliWang The library was updated recently (beginning of the month), so I have to guess these api updates happened in the last week?

**Comment by renier** [comment]
Fixed in 2f3a6fb
