### ISSUE TITLE
Network_Customer_Subnet is missing deleteObject method

### ISSUE THREAD

**Issue by JunliWang** [softlayer/softlayer-go#59]
metadata service is missing this method, I've opened a SL ticket to track it: https://control.softlayer.com/support/tickets/44117985.

**Comment by renier** [comment]
Not really a softlayer-go bug. You can ping us if you need a refresh of the library from the metadata.

**Comment by JunliWang** [comment]
the response from the ticket is: there is no deleteObject() in Network_Customer_Subnet, he suggests to use RemoveCustomerSubnetFromNetworkTunnel() in Network_Tunnel_Module_Context instead.
