### ISSUE TITLE
New feature: Logging with flag 

### ISSUE THREAD

**Issue by EdwardStudy** [softlayer/softlayer-go#61]
Hi, I am a dev of softlayer-cpi. In our old scenario, we use `bosh-utils/logger` to print logs with flags of information, like package name, etc. So we change softlayer-go client lib to customize logging format. But we fall behind your softlayer-go repo. 

So how about enabling an option of `softlayer-go` session to set log format.

An example below:
```
const mainLogFlag = "main"
logger.Info(mainLogFlag, "session: home dir could not be determined. Skipping read of ~/.softlayer.")
```

When we set a logging flag, The log contains a tag string to target our log location, result in current like this:

```
log.Println("[main] session: home dir could not be determined. Skipping read of ~/.softlayer.")
```
This setting's advantage is that improve debug and error tracking. In a more complicated scenario, clear and directly log format can help our operations to location issues.

Except for the package name, other info also can be provide for help.

I help the purpose can enhance the softlayer-go.

**Comment by renier** [comment]
Let's see it as a PR. Not sure if you intend to introduce a new logger package or what. I would not like to rely on any external loggers, though.
