### ISSUE TITLE
Upgrade virtual guest gives HTTP 500 error

### ISSUE THREAD

**Issue by Praveengostu** [softlayer/softlayer-go#66]
When trying to update the network speed attribute of virtual guest from 10 to 100 it gives error
 Couldn't upgrade virtual guest: SoftLayer_Exception_Order_Item_Invalid: Invalid price 100 Mbps Public & Private Network Uplinks (Dedicated Host) (203859) provided on the order container. Please select a dedicated instance Uplink Port Speeds price to order a dedicated instance. (HTTP 500)

**Comment by renier** [comment]
Please, share the code you are using.

**Comment by Praveengostu** [comment]
I was running the UAT "TestAccSoftLayerVirtualGuest_Basic" from https://github.com/softlayer/terraform-provider-softlayer
```TF_ACC=1 go test ./softlayer -v -run=TestAccSoftLayerVirtualGuest_Basic -timeout 1440m
=== RUN   TestAccSoftLayerVirtualGuest_Basic
The ID is 39351883
--- FAIL: TestAccSoftLayerVirtualGuest_Basic (236.63s)
	testing.go:280: Step 1 error: Error applying: 1 error(s) occurred:
		
		* softlayer_virtual_guest.terraform-acceptance-test-1: 1 error(s) occurred:
		
		* softlayer_virtual_guest.terraform-acceptance-test-1: Couldn't upgrade virtual guest: SoftLayer_Exception_Order_Item_Invalid: Invalid price 100 Mbps Public & Private Network Uplinks (Dedicated Host) (203859) provided on the order container. Please select a dedicated instance Uplink Port Speeds price to order a dedicated instance. (HTTP 500)
FAIL
exit status 1
FAIL	github.com/softlayer/terraform-provider-softlayer/softlayer	238.603s```

**Comment by Praveengostu** [comment]
HI Could you please update on this or let us know if you need more information
