### ISSUE TITLE
Creating Security Group gives Function (\"createObject\") is not a valid method for this service.

### ISSUE THREAD

**Issue by sakshiag** [softlayer/softlayer-go#67]
When I am trying to create the security group I am getting the following error:

2017/10/03 16:19:15 [DEBUG] Request URL:  POST https://api.softlayer.com/rest/v3/SoftLayer_Network_SecurityGroup.json
2017/10/03 16:19:15 [DEBUG] Parameters:  {"parameters":[[{"description":"for testing","name":"test_security_sakshi"}]]}
2017/10/03 16:19:17 [DEBUG] Response:  {"error":"Function (\"createObject\") is not a valid method for this service.","code":"SoftLayer_Exception_Public"}
SoftLayer_Exception_Public: Function ("createObject") is not a valid method for this service. (HTTP 404)

Code which I tried running 

func doCreateSecurityGroupTest(sess *session.Session) {

	service := services.GetNetworkSecurityGroupService(sess)
	// Create a Security Group

	opts := []datatypes.Network_SecurityGroup{
		{
			Name:        sl.String("test_security_sakshi"),
			Description: sl.String("for testing"),
		},
	}

	res, err := service.CreateObjects(opts)

	if err != nil {
		fmt.Printf("%s\n", err)

	} else {
		fmt.Printf("\nNew Security Group created with ID %d\n", *res[0].Id)

	}
}

**Comment by renier** [comment]
This is a bug with the API. Open a question on StackOverflow tagged with `softlayer` to get attention to it.

**Comment by allmightyspiff** [comment]
http://sldn.softlayer.com/reference/services/SoftLayer_Network_SecurityGroup

http://sldn.softlayer.com/reference/services/softlayer_network_securitygroup/createobjects is what you are looking for. Try that

https://github.com/softlayer/softlayer-python/blob/master/SoftLayer/managers/network.py#L221 
is how the python client does it

**Comment by renier** [comment]
@allmightyspiff posting here to give @sakshiag some clarity.

The problem seems to be that a POST to https://api.softlayer.com/rest/v3/SoftLayer_Network_SecurityGroup.json makes the API internally default to ‘createObject’ but that method doesn’t even exist for that service. The general API behavior is to default to the create method for that service, usually ‘createObject’, but other times it is ‘createObjects’ plural.
