### ISSUE TITLE
network.go GetLoadBalancer  request method is set as Post

### ISSUE THREAD

**Issue by Praveengostu** [softlayer/softlayer-go#70]
When calling the the GetLoadBalancer method of network.go the request method is set as Post
Below is the trace log
Request URL:  POST https://api.softlayer.com/rest/v3/SoftLayer_Network_LBaaS_LoadBalancer/getLoadBalancer.json?objectMask=mask%5Bdatacenter%2Cmembers%2Clisteners.defaultPool%2Clisteners.defaultPool.sessionAffinity%5D

**Comment by renier** [comment]
@Praveengostu is the method call failing?

**Comment by Praveengostu** [comment]
@renier The method call is successful. Only concern is why the request method is Post rather than GET

**Comment by renier** [comment]
@Praveengostu The POST method is correct, since you have to pass an argument. Whenever you have to pass arguments in the body, the http method should be POST.
