### ISSUE TITLE
Could retry when API returned 'SoftLayer_Exception_WebService_RateLimitExceeded'

### ISSUE THREAD

**Issue by EdwardStudy** [softlayer/softlayer-go#75]
The response message is:`Rate limit of 50 requests for every 1 second(s) exceeded.`

Could we add retry logic to prevent RateLimit exceptions?

**Comment by renier** [comment]
We could. Care to submit a PR?

**Comment by EdwardStudy** [comment]
@renier And I found that a status code `429` indicates that the user has sent too many requests in a given amount of time ("rate limiting").  Could it be included in session retry?

**Comment by allmightyspiff** [comment]
I think it would be useful to have a more generalized retry functionality.  I've added something similar to the softlayer-python project, so I think I'll take a stab at adding one to this client as well.

**Comment by craigyam** [comment]
@renier @EdwardStudy @allmightyspiff  I did some testing with this as I'm also seeing this failure.  The problem I'm seeing is that the call is returning with a response code of 500 and no error.  The retry logic is only used when err != nil.  Looks like the response body would need to be read and parsed looking for SoftLayer_Exception_WebService_RateLimitExceeded.
@kaufers
