### ISSUE TITLE
Calling CreateObjects on NetworkGatewayVlanService complains about missing value that is set

### ISSUE THREAD

**Issue by srowles** [softlayer/softlayer-go#76]
I think I have a bug, I’m trying to automate association and routing of vlans, I’m submitting this object:

```
[{Entity:{} BypassFlag:0xc42023a870 Id:<nil> NetworkGateway:<nil> NetworkGatewayId:0xc42023a878 NetworkVlan:<nil> NetworkVlanId:0xc42023a880} {Entity:{} BypassFlag:0xc42023a888 Id:<nil> NetworkGateway:<nil> NetworkGatewayId:0xc42023a890 NetworkVlan:<nil> NetworkVlanId:0xc42023a898}]
```

via:

`gatewayVlan, err := NetworkGatewayVlanService.CreateObjects(templates)`

And I’m getting the error back:

```
SoftLayer_Exception_MissingParameter: No value was provided for 'networkVlanId' property (HTTP 500)
```

However using a similar command using just a single template and CreateObject works just fine with the same data structure.

I did another print to show the pointer values and they all have a valid and correct SL object ID set. networkVlanId really is set to a value not just a pointer to a zero value

Unfortunately I don’t have the option to loop the single CreateObject command that works as I’m associating multiple vlans to a single firewall and the command creates a transaction which would block subsequent calls from working

**Comment by srowles** [comment]
Output with debug on, real IDs replaced

```
2017/11/29 16:37:34 [DEBUG] Request URL:  POST https://api.softlayer.com/rest/v3/SoftLayer_Network_Gateway_Vlan.json
2017/11/29 16:37:34 [DEBUG] Parameters:  {"parameters":[[{"bypassFlag":false,"networkGatewayId":GATEWAYID_NUMBER,"networkVlanId":VALID_VLAN_ID},{"bypassFlag":false,"networkGatewayId":GATEWAYID_NUMBER,"networkVlanId":VALID_VLAN_ID_2}]]}
2017/11/29 16:37:37 [DEBUG] Response:  {"error":"No value was provided for 'networkVlanId' property","code":"SoftLayer_Exception_MissingParameter"}
```

**Comment by renier** [comment]
@srowles This looks like a bug in the API. You might want to open a ticket and point to this issue. Let me know how it goes. From the looks of that post body, it looks good (`networkVlanId`s are set).

**Comment by raulcabero** [comment]
@renier  this is not an issue with the API , see the image below using a REST call the method is working fine.
![image](https://user-images.githubusercontent.com/4942849/33682677-9a649e46-da9e-11e7-848e-e2db643a183a.png)

In the logs sent by @srowles  I can see that the REST call is calling by default the createObject method and not the createObjects method, so I think that is an issue with the Softlayer GO client

**Comment by renier** [comment]
@raulcabero I see. I think the client assumes that one or the other, createObject or createObjects, will exist as service methods, but not both. So it omits the method name for either expecting the api to default to the create method that exists internally. Here we have a case where a service has two create methods, one singular and one plural, and the default one is the singular one when you omit the method name from the REST url.

Then CreateObjects, if I always call it like `https://api.softlayer.com/rest/v3/<service>/CreateObjects.json`, even if that is the only create method for the service, I should not encounter any problems right?

**Comment by srowles** [comment]
@renier if you want me to try a patch, or specific modification, I'm happy to give that a try to valid it works prior to a fix.

**Comment by renier** [comment]
@srowles Ok. Look at https://github.com/softlayer/softlayer-go/blob/master/session/rest.go#L140

Simply remove createObjects from that diff, and try it. If you can find a service that only has createObjects and that change still works, bingo.

**Comment by srowles** [comment]
@renier so I can confirm that removing "createObjects" from the list enables the call I need to make to work fine :)

I don't have any code calling createObjects anywhere other than for this, so I can't help with the 2nd part.
