### ISSUE TITLE
Memory update for a VSI fails

### ISSUE THREAD

**Issue by ashishth09** [softlayer/softlayer-go#83]
Updating the memory from 2GB to 1 GB via `UpgradeVirtualGuest` in  virtual package fails with 

SoftLayer_Exception_Order_Item_Invalid: Invalid price 1 GB (Dedicated Host) (200339) provided on the order container. Please select a dedicated instance RAM price to order a dedicated instance. (HTTP 500)

https://api.softlayer.com/rest/v3.1/SoftLayer_Product_Package/46/getItemPrices. Here I see there are some dedicated host prices for memory now. Like

```<item><capacity>1</capacity><description>1 GB (Dedicated Host)</description><id>10217</id><itemTaxCategoryId>166</itemTaxCategoryId><keyName>RAM_1_UNIT_DEDICATED</keyName><softwareDescriptionId/><units>GB</units><upgradeItemId/></item></item>```.

We need to filter out based on this.

**Comment by edwardstudy** [comment]
@ashishth09 
Hi, I just ran the same API: `https://api.softlayer.com/rest/v3.1/SoftLayer_Product_Package/46/getItemPrices.` and did not find some `RAM_1_UNIT_DEDICATED ` items. But I also meet same `SoftLayer_Exception_Order_Item_Invalid ` when updating dedicated instance.
