### ISSUE TITLE
Empty return for FirstUpdate parameter 

### ISSUE THREAD

**Issue by gangesan** [softlayer/softlayer-go#86]
Hi,

I am using the softlayer-go to collect ticket information needed. Every ticket does not have the parameter FirstUpdate populated. I was wondering if you know why ... FirstUpdate *Ticket_Update `json:"firstUpdate,omitempty" xmlrpc:"firstUpdate,omitempty"`. 

Thanks,

Kaya

**Comment by renier** [comment]
@gangesan You should use StackOverflow for questions like these. Have you tried specifying an object mask?
