### ISSUE TITLE
Convert structs to interfaces

### ISSUE THREAD

**Issue by ScarletTanager** [softlayer/softlayer-go#95]
It would be really useful if we could separate interface from implementation, e.g.

```
type Network_Vlan interface {
   GetSubnets()...
}

type network_Vlan_impl struct {
  // All the members of the current struct
}

func (r network_Vlan_impl) GetSubnets() ([]Network_Subnet, error) {
}
```

For folks writing client code using your API library, this would make life a LOT easier, since we could use a tool like `counterfeiter` to gen up fakes easily for testing purposes.  As it stands, I have to hand-code my fakes, which is pretty laborious.  I know this would be a fairly massive refactor, but it would also be pretty straightforward, and think it would likely be doable without breaking current API consumers.

**Comment by renier** [comment]
We won't be looking at this. They way we have written tests is by using an http mock instead. Take a look at the tests `make test`. So you can instead mock out the response for an http request.
