### ISSUE TITLE
Unmarshal error since datatype mismatch

### ISSUE THREAD

**Issue by sio4** [softlayer/softlayer-go#99]
Hi, I am using `softlayer-go` for making automated ticket and recently there is some error while calling `CreateStandardTicket()`. The error message is 

    json: cannot unmarshal string into Go struct field Ticket.serviceProviderResourceId of type int

and I tried to check related calls and I found below:

https://github.com/softlayer/softlayer-go/blob/b48f721534f4df1c9e6e718f85ebd4c4d6f3e356/datatypes/ticket.go#L210

and

https://github.com/softlayer/softlayer-go/blob/b48f721534f4df1c9e6e718f85ebd4c4d6f3e356/session/rest.go#L113

The API SPEC for this is below:

https://softlayer.github.io/reference/datatypes/SoftLayer_Ticket/#serviceProviderResourceId

    serviceProviderResourceId
    A ticket's internal identifier at its service provider. Each ticket is defined by a unique identifier.
    Type: string

The code I made worked fine for a year so I guess the SPEC was changed recently. Anyway I cannot found any change log on the release notes on https://softlayer.github.io/ . Is there any another change logs for the API changes?

**Comment by renier** [comment]
The api metadata from where the softlayer-go datatypes are generated has now since been updated to treat this as a string.

**Comment by sio4** [comment]
Ok, Thanks.
